// Code generated by goenum. DO NOT EDIT.

package main

import (
	"database/sql/driver"
	"fmt"
	"github.com/donutnomad/goenum/enums"
	"iter"
)

// SwapStatus is a type that represents a single enum value.
// It combines the core information about the enum constant and its defined fields.
type SwapStatus struct {
	swapStatus
}

// Verify that SwapStatus implements the Enum interface
var _ enums.Enum[int, SwapStatus] = SwapStatus{}

// swapStatusContainer is the container for all enum values.
// It is private and should not be used directly use the public methods on the SwapStatus type.
type swapStatusContainer struct {
	_invalidSwapStatus SwapStatus

	//////////////////////////////////////// STEP1-START ///////////////////////////////////////////

	// pending (1)
	// 刚创建swap请求 / 还没有选择counterparty， 或者目标是银行，等待银行的同意
	Step1Pending SwapStatus

	/////// 售卖给银行内部流程-START

	// canceled (2)
	// 用户自己取消了
	// state: [final]
	Step1Canceled SwapStatus

	// step1_bank_mark_amount (3)
	// 银行标记了金额，正在等待checker同意; 如果意见不一致，回到pending
	// state: -> WaitSenderAcceptOrCancel, Step1Pending
	Step1BankMarkAmount SwapStatus
	// step1_bank_mark_canceled (4)
	// 银行标记为取消
	// state: -> Step1CanceledByBank, Step1Pending
	Step1BankMarkCanceled SwapStatus
	// canceled_by_bank (1090)
	// 被银行取消了
	// state: [final]
	Step1CanceledByBank SwapStatus

	/////// 售卖给银行内部流程-END

	//////////////////////////////////////// STEP1-END ///////////////////////////////////////////

	//////////////////////////////////////// STEP2-START ///////////////////////////////////////////

	// wait_counterparty_sign (2000)
	// 等待counterparty签名，等同于[waitSenderAcceptOrCancel]
	// tag: step2
	// state: -> WaitSenderBroadcast
	WaitCounterpartySign SwapStatus

	/////// 售卖给银行内部流程-START

	// wait_sender_accept_cancel (2000)
	// 等待发送者接受或者取消; 接受后，系统会自动使用钱包进行签名。
	// tag: step2
	// state: -> WaitSenderBroadcast
	WaitSenderAcceptOrCancel SwapStatus

	/////// 售卖给银行内部流程-END

	//////////////////////////////////////// STEP2-END ///////////////////////////////////////////

	// wait_sender_broadcast (3000)
	// 等待sender执行swap交易
	// tag: step3
	// state: -> WaitTxConfirm
	WaitSenderBroadcast SwapStatus

	// wait_tx_confirm (3001)
	// 等待tx确认
	// tag: step3
	// state: -> Success, Expired, Failed
	WaitTxConfirm SwapStatus

	// success (4000)
	// 成功
	// tag: step3
	// state: [final]
	Success SwapStatus

	// expired (5000)
	// 过期(超过了swap的deadline)
	// tag: step3
	// state: [final]
	Expired SwapStatus

	// failed (6000)
	// 失败(sender广播交易失败)
	// tag: step3
	// state: [final]
	Failed SwapStatus
}

// Swaps is a main entry point using the SwapStatus type.
// It is a container for all enum values and provides a convenient way to access all enum values and perform
// operations, with convenience methods for common use cases.
var Swaps = swapStatusContainer{
	_invalidSwapStatus: SwapStatus{
		swapStatus: _invalidSwapStatus,
	},
	Step1Pending: SwapStatus{
		swapStatus: step1Pending,
	},
	Step1Canceled: SwapStatus{
		swapStatus: step1Canceled,
	},
	Step1BankMarkAmount: SwapStatus{
		swapStatus: step1BankMarkAmount,
	},
	Step1BankMarkCanceled: SwapStatus{
		swapStatus: step1BankMarkCanceled,
	},
	Step1CanceledByBank: SwapStatus{
		swapStatus: step1CanceledByBank,
	},
	WaitCounterpartySign: SwapStatus{
		swapStatus: waitCounterpartySign,
	},
	WaitSenderAcceptOrCancel: SwapStatus{
		swapStatus: waitSenderAcceptOrCancel,
	},
	WaitSenderBroadcast: SwapStatus{
		swapStatus: waitSenderBroadcast,
	},
	WaitTxConfirm: SwapStatus{
		swapStatus: waitTxConfirm,
	},
	Success: SwapStatus{
		swapStatus: success,
	},
	Expired: SwapStatus{
		swapStatus: expired,
	},
	Failed: SwapStatus{
		swapStatus: failed,
	},
}

// swapstatusNamesMap maps enum values to their names array
var swapstatusNamesMap = map[SwapStatus][]string{
	Swaps._invalidSwapStatus: {
		"_invalidSwapStatus",
	},
	Swaps.Step1Pending: {
		"pending",
	},
	Swaps.Step1Canceled: {
		"canceled",
	},
	Swaps.Step1BankMarkAmount: {
		"step1_bank_mark_amount",
	},
	Swaps.Step1BankMarkCanceled: {
		"step1_bank_mark_canceled",
	},
	Swaps.Step1CanceledByBank: {
		"canceled_by_bank",
	},
	Swaps.WaitCounterpartySign: {
		"wait_counterparty_sign",
	},
	Swaps.WaitSenderAcceptOrCancel: {
		"wait_sender_accept_cancel",
	},
	Swaps.WaitSenderBroadcast: {
		"wait_sender_broadcast",
	},
	Swaps.WaitTxConfirm: {
		"wait_tx_confirm",
	},
	Swaps.Success: {
		"success",
	},
	Swaps.Expired: {
		"expired",
	},
	Swaps.Failed: {
		"failed",
	},
}
// swapstatusTagsMap maps enum values to their tags array
var swapstatusTagsMap = map[SwapStatus][]string{
	Swaps.WaitCounterpartySign: {
		"step2",
	},
	Swaps.WaitSenderAcceptOrCancel: {
		"step2",
	},
	Swaps.WaitSenderBroadcast: {
		"step3",
	},
	Swaps.WaitTxConfirm: {
		"step3",
	},
	Swaps.Success: {
		"step3",
	},
	Swaps.Expired: {
		"step3",
	},
	Swaps.Failed: {
		"step3",
	},
}

// SwapsRaw is a type alias for the underlying enum type swapStatus.
// It provides direct access to the raw enum values for cases where you need
// to work with the underlying type directly.
type SwapsRaw = swapStatus

// allSlice returns a slice of all enum values.
func (t swapStatusContainer) allSlice() []SwapStatus {
	return []SwapStatus{
		Swaps._invalidSwapStatus,
		Swaps.Step1Pending,
		Swaps.Step1Canceled,
		Swaps.Step1BankMarkAmount,
		Swaps.Step1BankMarkCanceled,
		Swaps.Step1CanceledByBank,
		Swaps.WaitCounterpartySign,
		Swaps.WaitSenderAcceptOrCancel,
		Swaps.WaitSenderBroadcast,
		Swaps.WaitTxConfirm,
		Swaps.Success,
		Swaps.Expired,
		Swaps.Failed,
	}
}

// Val implements the Enum interface.
func (t SwapStatus) Val() int {
	return int(t.swapStatus)
}

// All implements the Enum interface.
func (t SwapStatus) All() iter.Seq[SwapStatus] {
	return func(yield func(SwapStatus) bool) {
		for _, v := range Swaps.allSlice() {
			if !v.IsValid() {
				continue
			}
			if !yield(v) {
				return
			}
		}
	}
}

// IsValid implements the Enum interface.
func (t SwapStatus) IsValid() bool {
	if t == Swaps._invalidSwapStatus {
		return false
	}
	return true
}

// Name implements the Enum interface.
// Returns the first name of the enum value.
func (t SwapStatus) Name() string {
	if names, ok := swapstatusNamesMap[t]; ok && len(names) > 0 {
		return names[0]
	}
	return ""
}

// NameWith returns the name at the specified index.
// If the index is out of bounds, returns the last name.
func (t SwapStatus) NameWith(idx int) string {
	names, ok := swapstatusNamesMap[t]
	if !ok || len(names) == 0 {
		return ""
	}
	if idx < 0 || idx >= len(names) {
		return names[len(names)-1]
	}
	return names[idx]
}

// Names returns all names of the enum value.
func (t SwapStatus) Names() []string {
	if names, ok := swapstatusNamesMap[t]; ok {
		return names
	}
	return []string{}
}

// String implements the Stringer interface.
func (t SwapStatus) String() string {
	if names, ok := swapstatusNamesMap[t]; ok && len(names) > 0 {
		return names[0]
	}
	return fmt.Sprintf("swapStatus(%v)", t.swapStatus)
}

// SerdeFormat implements the Enum interface.
func (t SwapStatus) SerdeFormat() enums.Format {
	return enums.FormatValue
}

// FromName implements the Enum interface.
func (t SwapStatus) FromName(name string) (SwapStatus, bool) {
	for enumValue, names := range swapstatusNamesMap {
		for _, n := range names {
			if n == name {
				return enumValue, enumValue.IsValid()
			}
		}
	}
	var zero SwapStatus
	return zero, false
}

// FromValue implements the Enum interface.
func (t SwapStatus) FromValue(value int) (SwapStatus, bool) {
	for v := range Swaps.All() {
		if v.Val() == value {
			return v, true
		}
	}
	var zero SwapStatus
	return zero, false
}

// Step2Slice returns all enum values that have the "step2" tag.
func (t swapStatusContainer) Step2Slice() []SwapStatus {
	var result []SwapStatus
	for _, v := range t.allSlice() {
		if v.IsStep2() {
			result = append(result, v)
		}
	}
	return result
}

// IsStep2 returns true if this enum value has the "step2" tag.
func (t SwapStatus) IsStep2() bool {
	if tags, ok := swapstatusTagsMap[t]; ok {
		for _, tag := range tags {
			if tag == "step2" {
				return true
			}
		}
	}
	return false
}

// Step3Slice returns all enum values that have the "step3" tag.
func (t swapStatusContainer) Step3Slice() []SwapStatus {
	var result []SwapStatus
	for _, v := range t.allSlice() {
		if v.IsStep3() {
			result = append(result, v)
		}
	}
	return result
}

// IsStep3 returns true if this enum value has the "step3" tag.
func (t SwapStatus) IsStep3() bool {
	if tags, ok := swapstatusTagsMap[t]; ok {
		for _, tag := range tags {
			if tag == "step3" {
				return true
			}
		}
	}
	return false
}

// All container methods for convenience
func (t swapStatusContainer) All() iter.Seq[SwapStatus] {
	return SwapStatus{}.All()
}

func (t swapStatusContainer) FromName(name string) (SwapStatus, bool) {
	return SwapStatus{}.FromName(name)
}

func (t swapStatusContainer) FromValue(value int) (SwapStatus, bool) {
	return SwapStatus{}.FromValue(value)
}

// Scan implements the database/sql.Scanner interface for SwapStatus.
func (t *SwapStatus) Scan(value any) error {
	result, err := enums.SQLScan(*t, value)
	if err != nil {
		return err
	}
	*t = *result
	return nil
}

// Value implements the database/sql/driver.Valuer interface for SwapStatus.
func (t SwapStatus) Value() (driver.Value, error) {
	return enums.SQLValue(t)
}

// MarshalJSON implements the json.Marshaler interface for SwapStatus.
func (t SwapStatus) MarshalJSON() ([]byte, error) {
	return enums.MarshalJSON(t, t.swapStatus)
}

// UnmarshalJSON implements the json.Unmarshaler interface for SwapStatus.
func (t *SwapStatus) UnmarshalJSON(data []byte) error {
	result, err := enums.UnmarshalJSON(*t, data)
	if err != nil {
		return err
	}
	*t = *result
	return nil
}

// CanTransitionTo checks if the current state can transition to the target state.
func (t SwapStatus) CanTransitionTo(target SwapStatus) bool {
	transitions := t.ValidTransitions()
	for _, validTarget := range transitions {
		if validTarget == target {
			return true
		}
	}
	return false
}

// ValidTransitions returns all valid target states that this state can transition to.
func (t SwapStatus) ValidTransitions() []SwapStatus {
	if t == Swaps.Step1BankMarkAmount {
		return []SwapStatus{
			Swaps.WaitSenderAcceptOrCancel,
			Swaps.Step1Pending,
		}
	}
	if t == Swaps.Step1BankMarkCanceled {
		return []SwapStatus{
			Swaps.Step1CanceledByBank,
			Swaps.Step1Pending,
		}
	}
	if t == Swaps.WaitCounterpartySign {
		return []SwapStatus{
			Swaps.WaitSenderBroadcast,
		}
	}
	if t == Swaps.WaitSenderAcceptOrCancel {
		return []SwapStatus{
			Swaps.WaitSenderBroadcast,
		}
	}
	if t == Swaps.WaitSenderBroadcast {
		return []SwapStatus{
			Swaps.WaitTxConfirm,
		}
	}
	if t == Swaps.WaitTxConfirm {
		return []SwapStatus{
			Swaps.Success,
			Swaps.Expired,
			Swaps.Failed,
		}
	}
	return []SwapStatus{}
}

// IsTerminalState returns true if this state is a terminal (final) state.
func (t SwapStatus) IsTerminalState() bool {
	if t == Swaps.Step1Canceled {
		return true
	}
	if t == Swaps.Step1CanceledByBank {
		return true
	}
	if t == Swaps.Success {
		return true
	}
	if t == Swaps.Expired {
		return true
	}
	if t == Swaps.Failed {
		return true
	}
	return false
}

// TerminalStateSlice returns a slice of all terminal states.
func (t SwapStatus) TerminalStateSlice() []SwapStatus {
	return []SwapStatus{
		Swaps.Step1Canceled,
		Swaps.Step1CanceledByBank,
		Swaps.Success,
		Swaps.Expired,
		Swaps.Failed,
	}
}
